# Generated by Django 4.0.1 on 2022-01-26 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField()),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 1, 26, 12, 26, 26, 313801, tzinfo=utc))),
                ('user_has_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Создан')),
            ],
        ),
    ]
