# Generated by Django 4.0.1 on 2022-02-04 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 4, 17, 40, 53, 56397, tzinfo=utc)),
        ),
    ]
