# Generated by Django 4.0.1 on 2022-02-05 01:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_notification_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 1, 11, 16, 374653, tzinfo=utc)),
        ),
    ]
