# Generated by Django 4.0.1 on 2022-02-06 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_notification_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 12, 8, 29, 531367, tzinfo=utc)),
        ),
    ]
