# Generated by Django 4.0.1 on 2022-02-08 15:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_notification_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 15, 41, 27, 76839, tzinfo=utc)),
        ),
    ]
