# Generated by Django 4.0.1 on 2022-02-14 11:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0006_alter_notification_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 11, 33, 12, 800739, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_importance', models.IntegerField()),
                ('task_name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('task_description', models.CharField(blank=True, max_length=128, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Создан')),
                ('task_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
