# Generated by Django 4.0.1 on 2022-01-23 16:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, verbose_name='Шифр')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='Срок экспертизы')),
                ('next_upload', models.DateField(blank=True, null=True, verbose_name='Следующая загрузка')),
                ('project_type', models.IntegerField(blank=True, choices=[(2, 'Линейный'), (1, 'Площадной')], verbose_name='Тип объекта')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ГИП')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='StandardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=256)),
                ('project_type', models.IntegerField(blank=True, choices=[(2, 'Линейный'), (1, 'Площадной')])),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование')),
                ('abbreviation', models.CharField(blank=True, max_length=16, verbose_name='Аббревиатура')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company', verbose_name='Организация')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_id', to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project', verbose_name='Проект')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='№')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('body', models.CharField(max_length=1024, verbose_name='Содержание')),
                ('link', models.CharField(blank=True, max_length=256, verbose_name='Ссылка')),
                ('basis', models.CharField(blank=True, max_length=512, verbose_name='Основание')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Эксперт')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Замечание',
                'verbose_name_plural': 'Замечания',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование')),
                ('doc_path', models.FileField(upload_to='main_docs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Путь')),
                ('version', models.IntegerField(verbose_name='Версия')),
                ('variation', models.IntegerField(verbose_name='Изменение')),
                ('md5', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('Первичные', 'Первичные замечания'), ('Повторные', 'Повторные замечания'), ('Загружено', 'Загружено'), ('Просрочено', 'Просрочено'), ('Положительное', 'Положительное'), ('Отрицательное', 'Отрицательное')], max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Создан')),
                ('note', models.CharField(blank=True, max_length=128, verbose_name='Примечание')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('body', models.CharField(max_length=1024, verbose_name='Содержание')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.document', verbose_name='Документ')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='main.comment', verbose_name='Переслать')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.CharField(max_length=512, verbose_name='Лист')),
                ('code', models.CharField(choices=[(1, 'Введение усовершенствований'), (2, 'Изменение стандартов и норм'), (3, 'Дополнительные требования заказчика'), (4, 'Устранение ошибок'), (5, 'Другие причины')], max_length=1, verbose_name='Шифр')),
                ('note', models.CharField(blank=True, max_length=128, verbose_name='Примечания')),
                ('body', models.CharField(max_length=256, verbose_name='Содержание')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.document', verbose_name='Документ')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Вид корректирования',
                'verbose_name_plural': 'Виды корректирования',
            },
        ),
    ]
