# Generated by Django 4.0.1 on 2022-01-14 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('body', models.CharField(max_length=1024)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='adjustment',
            old_name='document_id',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='adjustment',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='remark',
            old_name='expert_id',
            new_name='expert',
        ),
        migrations.RenameField(
            model_name='remark',
            old_name='section_id',
            new_name='section',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.document'),
        ),
        migrations.AddField(
            model_name='comment',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='main.comment'),
        ),
    ]
