# Generated by Django 4.0.1 on 2022-01-25 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_company_email_alter_company_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjustment',
            options={'verbose_name': 'Корректировки', 'verbose_name_plural': 'Корректировки'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.document', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='recipient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='main.comment', verbose_name='Переслать'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, choices=[('Первичные', 'Первичные замечания'), ('Повторные', 'Повторные замечания'), ('Загружено', 'Загружено'), ('Просрочено', 'Просрочено'), ('Положительное', 'Положительное'), ('Отрицательное', 'Отрицательное')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ГИП'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Площадной'), (2, 'Линейный')], null=True, verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='section',
            name='abbreviation',
            field=models.CharField(max_length=16, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='section',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.company', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='standardsection',
            name='project_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Площадной'), (2, 'Линейный')], null=True),
        ),
    ]
