# Generated by Django 4.0.1 on 2022-02-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Площадной'), (2, 'Линейный')], null=True, verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='standardsection',
            name='project_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Площадной'), (2, 'Линейный')], null=True),
        ),
    ]
