# Generated by Django 4.0.1 on 2022-01-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment_rename_document_id_adjustment_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='document',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='document',
            name='section',
        ),
        migrations.RemoveField(
            model_name='project',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section',
            name='company',
        ),
        migrations.RemoveField(
            model_name='section',
            name='responsible',
        ),
        migrations.DeleteModel(
            name='Adjustment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Remark',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
