# Generated by Django 4.0.1 on 2022-01-14 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_company_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_remove_comment_author_remove_comment_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('exp_date', models.DateField()),
                ('next_upload', models.DateField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('body', models.CharField(max_length=1024)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.section')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('doc_path', models.FileField(upload_to='main_docs')),
                ('version', models.IntegerField()),
                ('variation', models.IntegerField()),
                ('md5', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('Первичные', 'Первичные замечания'), ('Повторные', 'Повторные замечания'), ('Загружено', 'Загружено'), ('Просрочено', 'Просрочено'), ('Положительное', 'Положительное'), ('Отрицательное', 'Отрицательное')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=128)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.section')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('body', models.CharField(max_length=1024)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.document')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='main.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.CharField(max_length=512)),
                ('code', models.CharField(choices=[(1, 'Введение усовершенствований'), (2, 'Изменение стандартов и норм'), (3, 'Дополнительные требования заказчика'), (4, 'Устранение ошибок'), (5, 'Другие причины')], max_length=1)),
                ('note', models.CharField(blank=True, max_length=128)),
                ('body', models.CharField(max_length=256)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.document')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.section')),
            ],
        ),
    ]
