# Generated by Django 4.0.1 on 2022-01-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_comment_recipient_remove_comment_reply_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_comments', to='main.document', verbose_name='Документ'),
        ),
    ]
