# Generated by Django 4.0.1 on 2022-01-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_section_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='basis',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='remark',
            name='link',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
