# Generated by Django 4.0.1 on 2022-01-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remark_basis_remark_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='number',
            field=models.IntegerField(default=4),
        ),
    ]
