# Generated by Django 4.0.1 on 2022-01-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
