# Generated by Django 4.0.1 on 2022-01-21 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0011_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandartSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=256)),
                ('project_type', models.CharField(blank=True, choices=[('линейный', 'Линейный объект'), ('площадной', 'Площадной объект')], max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='project',
            name='next_upload',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='expert',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='responsible',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
