# Generated by Django 4.0.1 on 2022-01-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_standartsection_section_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standartsection',
            name='project_type',
            field=models.IntegerField(blank=True, choices=[(2, 'Линейный объект'), (1, 'Площадной объект')], max_length=1),
        ),
    ]
