# Generated by Django 4.0.1 on 2022-01-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_standartsection_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=256)),
                ('project_type', models.IntegerField(blank=True, choices=[(1, 'Площадной объект'), (2, 'Линейный объект')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='StandartSection',
        ),
    ]
