# Generated by Django 4.0.1 on 2022-01-21 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_standardsection_delete_standartsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='standardsection',
            name='project_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Площадной объект'), (2, 'Линейный объект')]),
        ),
    ]
