# Generated by Django 4.0.1 on 2022-01-21 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_alter_section_responsible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
