# Generated by Django 4.0.1 on 2022-01-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='company')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=30, null=True, verbose_name='patronymic'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='usercompanyinfo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.company'),
        ),
    ]
