# Generated by Django 4.0.1 on 2022-01-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone',
        ),
    ]
