# Generated by Django 4.0.1 on 2022-01-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_company_email_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompanyinfo',
            name='position',
            field=models.CharField(blank=True, max_length=128, verbose_name='position'),
        ),
    ]
